/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Arbol;
import Clases.Nodo;
import Clases.Proceso;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juegos
 */
public class Arbolito extends javax.swing.JFrame {

    /**
     * Creates new form Frame_P1U3
     */
    Proceso P;
    Arbol semilla;
    DefaultTableModel mod;
    Round_Robin rr;
    int modo;
    Login_Frame lf;

    public Arbolito() {
        initComponents();
        P = new Proceso();                                  //Inicializamos una Variable Proceso para Insertar en el arbol
        semilla = new Arbol();                              //Inicializamos el arbol
        mod = (DefaultTableModel) JtableDatos.getModel();   //Inicializamos el Modelo de la Tabla que graficará el arbol
        rr = new Round_Robin();                             //Llamamos a la interfaz de Control
        rr.a = this;                                        //Referenciamos a este Frame en el de la Interfaz de Control
        System.out.println("modo Ar= " + modo);
        //rr.modo = this.modo;
    }

    public void recmodo(int mod){
    
        this.modo = lf.modo;
    }
    
    private void random(java.awt.event.ActionEvent evt) {   //Método que asigna los tiempos aleatoriamente
        Random r = new Random();
        this.jtxfTiempoEjecucion.setText((1 + r.nextInt(10)) + "");
        this.jtxfTiempoLlegada.setText((1 + r.nextInt(10)) + "");
        this.BtnAgregarActionPerformed(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPreO = new javax.swing.JButton();
        BtnPosO = new javax.swing.JButton();
        BtnInO = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        CBProceso = new javax.swing.JComboBox<>();
        BtnBuscar = new javax.swing.JButton();
        jlblQuantum = new javax.swing.JLabel();
        jspQuantum = new javax.swing.JSpinner();
        jlblTiempoLlegada = new javax.swing.JLabel();
        jtxfTiempoLlegada = new javax.swing.JTextField();
        jlblTiempoEjecucion = new javax.swing.JLabel();
        jtxfTiempoEjecucion = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtableDatos = new javax.swing.JTable();
        BtnIniciar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnAcercade = new javax.swing.JButton();
        jbtnSalir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        BtnPreO.setText("Pre-Orden");
        BtnPreO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPreOActionPerformed(evt);
            }
        });

        BtnPosO.setText("Pos-Orden");
        BtnPosO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPosOActionPerformed(evt);
            }
        });

        BtnInO.setText("In-Orden");
        BtnInO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInOActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        jlblQuantum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblQuantum.setText("Quantum");

        jspQuantum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblTiempoLlegada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTiempoLlegada.setText("Tiempo LLegada");

        jtxfTiempoLlegada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxfTiempoLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfTiempoLlegadaActionPerformed(evt);
            }
        });

        jlblTiempoEjecucion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTiempoEjecucion.setText("Tiempo de Ejecucion");

        jtxfTiempoEjecucion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxfTiempoEjecucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfTiempoEjecucionActionPerformed(evt);
            }
        });

        BtnAgregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        JtableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Proceso", "Llegada", "Tiempo Ejec.", "Quantum"
            }
        ));
        jScrollPane3.setViewportView(JtableDatos);

        BtnIniciar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BtnIniciar.setText("Iniciar");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        jbtnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jbtnAcercade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnAcercade.setText("?");
        jbtnAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAcercadeActionPerformed(evt);
            }
        });

        jbtnSalir1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnSalir1.setText("CERRAR SESIÓN");
        jbtnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTiempoLlegada)
                            .addComponent(jtxfTiempoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxfTiempoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTiempoEjecucion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnPreO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPosO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnInO)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnIniciar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnAcercade)
                            .addGap(110, 110, 110)
                            .addComponent(jbtnSalir1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblQuantum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTiempoLlegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTiempoEjecucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxfTiempoLlegada)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxfTiempoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnPreO)
                            .addComponent(BtnPosO)
                            .addComponent(BtnInO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEliminar)
                            .addComponent(CBProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBuscar)))
                    .addComponent(BtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAcercade)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPreOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPreOActionPerformed
        mod.setRowCount(0);                         //Se vacia la tabla
        mod.setColumnCount(4);                      //Se asigna el numero de Columnas
        semilla.preorden(semilla.getRaiz(), mod);   //Se llama al metodo de Ordenamineto
    }//GEN-LAST:event_BtnPreOActionPerformed

    private void BtnPosOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPosOActionPerformed
        mod.setRowCount(0);                         //Se vacia la tabla
        mod.setColumnCount(4);                      //Se asigna el numero de Columnas
        semilla.posorden(semilla.getRaiz(), mod);   //Se llama al metodo de Ordenamineto
    }//GEN-LAST:event_BtnPosOActionPerformed

    private void BtnInOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInOActionPerformed
        mod.setRowCount(0);                         //Se vacia la tabla
        mod.setColumnCount(4);                      //Se asigna el numero de Columnas
        semilla.inorden(semilla.getRaiz(), mod);    //Se llama al metodo de Ordenamineto
    }//GEN-LAST:event_BtnInOActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        Nodo[] arrEnc = new Nodo[1];                                       //Se crea un arreglo de clase Nodo para guardar el proceso
        boolean band;                                                       //Se crea un variable bandera
        char n = CBProceso.getSelectedItem().toString().charAt(0);          //Se obtiene el numero de proceso del Combo Box
        band = semilla.buscarNodo(n, arrEnc);                               //Se utiliza la variable bandera para saber si el proceso a eliminar existe

        if (band) {
            semilla.eliminarNodo(arrEnc[0]);                                //Si existe se elimina del arbol,
        }
        CBProceso.removeItemAt(CBProceso.getSelectedIndex());               //del ComboBox
        DefaultTableModel m = (DefaultTableModel) rr.JtableDatos.getModel(); //de las Tablas
        DefaultTableModel l = (DefaultTableModel) rr.jtblAccess.getModel();
        for (int i = 0; i < m.getRowCount(); i++) {
            if (m.getValueAt(i, 0).toString().charAt(0) == n) {
                m.removeRow(i);
                l.removeRow(i);
            }
        }
        for (int j = 0; j < rr.ProcesosEspera.Length(); j++) {
            if (rr.ProcesosEspera.getProceso(j).getNumProceso() == n) {
                rr.ProcesosEspera.RemoveSelect(j);
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void jtxfTiempoLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfTiempoLlegadaActionPerformed
        BtnAgregarActionPerformed(evt);                                     //Presione "enter" para ingresar
    }//GEN-LAST:event_jtxfTiempoLlegadaActionPerformed

    private void jtxfTiempoEjecucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfTiempoEjecucionActionPerformed
        BtnAgregarActionPerformed(evt);                                     //Presione "enter" para ingresar
    }//GEN-LAST:event_jtxfTiempoEjecucionActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        //VALIDA QUE LOS TEXTFIELD NO ESTEN VACIOS
        try {
            if (!jtxfTiempoLlegada.getText().trim().equalsIgnoreCase("") && !jtxfTiempoEjecucion.getText().trim().equalsIgnoreCase("")) {
                //Verifica que el quantum sea mayor que 0
                if (Integer.parseInt(jspQuantum.getValue().toString()) > 0) {
                    Ingresar();                                             //Metodo de Ingreso al Arbol
                    jspQuantum.setEnabled(false);                           //Para evitar problemas de diferencia de quantums
                } else {
                    JOptionPane.showMessageDialog(this, "Ingresar un Quantum valido mayor a 0");
                }
            } else {
                random(evt);                                                //Llama al metodo de Aleatorios si esta vacio cualquier campo
            }
        } catch (Exception e) {
            //EN CASO DE ERROR, ENVIA UN MENSAJE
            JOptionPane.showMessageDialog(this, "Ingrese datos validos");
            System.out.println("" + e);

        }


    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        //Llama al Frame de Control
        rr.setJspQuantum(Integer.parseInt(jspQuantum.getValue().toString()));                                //  
        rr.setVisible(true);
        rr.modo = lf.modo;
        this.setVisible(false);
    }//GEN-LAST:event_BtnIniciarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAcercadeActionPerformed
        JOptionPane.showMessageDialog(this,
                "INGENIERIA DE SISTEMAS COMPUTACIONALES \n\n"
                + "PROYECTO ROUND ROBIN PARA LA CLASE DE SISTEMAS OPERATIVOS\n"
                + "Version:  1.0 \n\n"
                + "PROGRAMA HECHO POR: \n "
                + "Viviana Lizbeth Zavala Mireles   #17130855\n"
                + "Julio Mendez Lira   #17130806\n"
                + "Erick Ortiz Rios   #17130816\n"
                + "Artemio Pánuco González    #16130830\n"
                + "Enrique Antonio Belmarez Meraz   #17130765\n",
                "Acerca De",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnAcercadeActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        Nodo [] a = new Nodo[1];
        boolean band = semilla.buscarNodo(this.CBProceso.getSelectedItem().toString().charAt(0), a);
        
        if(band)
            JOptionPane.showMessageDialog(this, "Si existe el Proceso " + CBProceso.getSelectedItem().toString(), "Atención", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "No Existe el Proceso " + CBProceso.getSelectedItem().toString(), "Atención", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void jbtnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalir1ActionPerformed
        lf = new Login_Frame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnSalir1ActionPerformed

    //Ingresa los datos en el Frame de Control
    public void Ingresar() {
        if (!jtxfTiempoEjecucion.getText().equals("") && !jtxfTiempoLlegada.getText().equals("")) {
            Random r = new Random();
            rr.jspQuantum = this.jspQuantum;  //Asigna el Quanrum em el FC
            rr.jtxfTiempoEjecucion = this.jtxfTiempoEjecucion; //Asigna el Tirmpo de Ejecución em el FC
            rr.jtxfTiempoLlegada = this.jtxfTiempoLlegada; //Asigna el Tiempo de Llegada em el FC
            int n = r.nextInt(50) + 64;     //Asigna el Numero de Proceso
            //Verifica si el nombre ya existia
            for (int j = 0; j < rr.getProcesosEspera().Length(); j++) {
                if (rr.getProcesosEspera().getProceso(j).getNumProceso() == n) {
                    n = r.nextInt(40) + 64;
                };
            }
            //Inserta el Proceso en el arbol
            semilla.insertar(new Proceso((char) n,
                    Integer.parseInt(this.jtxfTiempoLlegada.getText()),
                    Integer.parseInt(this.jtxfTiempoEjecucion.getText()),
                    Integer.parseInt(this.jspQuantum.getValue().toString()),
                    Integer.parseInt(this.jtxfTiempoEjecucion.getText())));
            //Inserta el numero de proceso en el CB para su eliminacion o busqueda
            this.CBProceso.addItem((char) n + "");
            //Ingresa el proceso en el FC
            rr.Ingresar(n);
        } else {
            System.out.println("LLena los Datos");
        }
    }

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arbolito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arbolito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arbolito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arbolito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new Arbolito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnInO;
    private javax.swing.JButton BtnIniciar;
    private javax.swing.JButton BtnPosO;
    private javax.swing.JButton BtnPreO;
    private javax.swing.JComboBox<String> CBProceso;
    private javax.swing.JTable JtableDatos;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnAcercade;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnSalir1;
    private javax.swing.JLabel jlblQuantum;
    private javax.swing.JLabel jlblTiempoEjecucion;
    private javax.swing.JLabel jlblTiempoLlegada;
    private javax.swing.JSpinner jspQuantum;
    private javax.swing.JTextField jtxfTiempoEjecucion;
    private javax.swing.JTextField jtxfTiempoLlegada;
    // End of variables declaration//GEN-END:variables
}
